### PR TITLE
fix: make "People and body" category work in Firefox content script

### LINKED ISSUE #356: "People and body" section doesn't work inside Firefox addon content script
When ran in Firefox addon's content script, opening "People and body" section doesnt work, it doesn't render emojis inside even though it switches the active section.
Error: `Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper` inside `cleanEmoji` function, specifically `emoji.skins = Array(len);`, seems that assigning to `emoji` causes this error but I wasn't able to figure out what's exactly wrong. Something about Firefox's sandbox

Related issue: https://github.com/dimdenGD/OldTwitter/issues/77

### PR DESCRIPTION
**Pull request by dimdenGD**
Fixes #356

### CODE REVIEW

File: src/database/utils/cleanEmoji.js [hunk 1]
```diff
@@ -4,6 +4,10 @@ export function cleanEmoji (emoji) {
   if (!emoji) {
     return emoji
   }
+  // if inside a Firefox content script, need to clone the emoji object to prevent Firefox from complaining about cross-origin object
+  if (typeof wrappedJSObject !== 'undefined') {
+      emoji = structuredClone(emoji)
```
Comment (nolanlawson) [inline src/database/utils/cleanEmoji.js:9]:
```suggestion
    emoji = structuredClone(emoji)
```

StandardJS is complaining about whitespace.

File: src/database/utils/cleanEmoji.js [hunk 2]
```diff
@@ -4,6 +4,10 @@ export function cleanEmoji (emoji) {
   if (!emoji) {
     return emoji
   }
+  // if inside a Firefox content script, need to clone the emoji object to prevent Firefox from complaining about cross-origin object
+  if (typeof wrappedJSObject !== 'undefined') {
```
Comment (nolanlawson) [inline src/database/utils/cleanEmoji.js:8]:
```suggestion
  /* istanbul ignore if */
  if (typeof wrappedJSObject !== 'undefined') {
```

**Comment by nolanlawson** [comment]
Thank you!
